// src/lib/ProjectsCard.svelte
<script lang="ts">
	import Card from "$lib/Card.svelte";
	const projects = [
		{
			name: "Chariz",
			description:
				"A payments processing platform and marketplace for app developers",
			link: "https://chariz.com",
		},
		{
			name: "Lyricify",
			description:
				"A lockscreen extension to view song lyrics on your iPhone",
			link: "https://chariz.com/buy/lyricify",
		},
		{
			name: "Canister",
			description:
				"A search engine for packages used by the iOS Jailbreaking community",
		},
	];
</script>

<Card>
	<h2>Latest Projects</h2>
	<hr />
	<div class="table">
		{#each projects as project}
			<div class="column">
				{#if project.link}
					<span>
						<a href="https://chariz.com/buy/lyricify" id="title">
							{project.name}:
						</a>
						{project.description}
					</span>
				{:else}
					<span>
						<span id="title">{project.name}</span>: {project.description}
					</span>
				{/if}
			</div>
		{/each}
	</div>
</Card>

<style>
	.table {
		display: flex;
		flex-direction: column;
	}

	.column {
		flex: 50%;
		margin: 8px;
		overflow-x: hidden;
		display: inline-flex;
	}

	#title {
		font-weight: bolder;
	}
</style>

// src/components/ProjectsCard.tsx
import React, { Component } from 'react'

const projects = [
	{
		name: 'Lyricify',
		description: 'iOS Runtime Modification Tweak allowing you to view song lyrics on the lockscreen',
		link: 'https://chariz.com/buy/lyricify/'
	},
	{
		name: 'Canister',
		description: 'API for querying packages and repositories commonly used in the Jailbreak Community',
		link: 'https://canister.me/'
	},
	{
		name: 'Chariz',
		description: 'A marketplace for iOS runtime tweaks and applications',
		link: 'https://chariz.com/'
	},
	{
		name: 'madebymirac',
		description: 'A wallpaper site showcasing works by Mirac',
		link: 'https://madebymirac.com/'
	},
	{
		name: 'Heron',
		description: 'A consolidated API with licensing, cryptography, and a database'
	}
]

export default class ProjectsCard extends Component {
	render() {
		return (
			<div className="card project-card">
				<h1>Active Projects</h1>
				<ul>
					{projects.map(project => {
						if (project.link) {
							return (
								<li key={project.name} className="list-object">
									<a className="list-link" href={project.link}>
										<strong style={{ textDecoration: 'underline' }}>{project.name}</strong>: {project.description}
									</a>
								</li>
							)
						} else {
							return (
								<li key={project.name} className="list-object">
									<strong>{project.name}</strong>: {project.description}
								</li>
							)
						}
					})}
				</ul>
			</div>
		)
	}
}
